/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package Lab;

public class Library {
	
	public static void main(String arg[]) {
		System.out.println("When there is a fire, commit and push.");
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
